Add iPhoneOS 15.6 and 16.5 SDKs
theos/sdks pull request #66
Opened 2023-11-12 22:01 UTC by leptos-null

What does this implement/fix? Explain your changes.
---------------------------------------------------
Adds iOS 15.6 and 16.5 SDKs

Does this close any currently open issues?
------------------------------------------
#62 

Any relevant logs, error output, etc?
-------------------------------------

When generating 15.6 SDK:

Seemingly not an issue, but I haven't seen the `dyld_shared_cache` errors before. I suspect it's related to being arm64e, but not sure. Spot-checking some private symbols, there doesn't appear to be anything missing.

```
Mach-o file (at path .../Symbols/System/Library/PrivateFrameworks/HomeKitCore.framework/HomeKitCore) has no symbol-table
Mach-o file (at path .../Symbols/System/Library/Frameworks/Accelerate.framework/Accelerate) has no symbol-table
Mach-o file (at path .../Symbols/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/vecLib) has no symbol-table
Mach-o file (at path .../Symbols/System/Library/Frameworks/CoreTelephony.framework/Support/libCommCenterCNTargetData.dylib) has no symbol-table
dyld_shared_cache file (at path .../Symbols/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e.1) has invalid images
dyld_shared_cache file (at path .../Symbols/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e.symbols) has invalid images
dyld_shared_cache file (at path .../Symbols/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e) has invalid images
dyld_shared_cache file (at path .../Symbols/System/DriverKit/System/Library/dyld/dyld_shared_cache_arm64e.symbols) has invalid images
dyld_shared_cache file (at path .../Symbols/System/DriverKit/System/Library/dyld/dyld_shared_cache_arm64e) has invalid images
```

When generating 16.5 SDK: 

(no issue)

```
Mach-o file (at path .../Symbols/System/Library/PrivateFrameworks/HomeKitCore.framework/HomeKitCore) has no symbol-table
Mach-o file (at path .../Symbols/System/Library/PrivateFrameworks/Message.framework/MailServices/IMAP.framework/IMAP) has no symbol-table
Mach-o file (at path .../Symbols/System/Library/Frameworks/Accelerate.framework/Accelerate) has no symbol-table
Mach-o file (at path .../Symbols/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/vecLib) has no symbol-table
Mach-o file (at path .../Symbols/System/Library/Frameworks/PassKit.framework/PassKit) has no symbol-table
```

Any other comments?
-------------------
Generated using `create_patched_sdk.sh` with the latest Xcode for each release; specifically:
- iOS 15.6 `->` Xcode 13.4.1
- iOS 16.5 `->` Xcode 14.3.1

Diffed public part of the SDKs against the respective Xcode SDKs and found no differences as expected.

Where has this been tested?
---------------------------
**Operating System:** macOS

**Target Platform:** iOS

**Toolchain Version:** `Apple clang version 15.0.0 (clang-1500.0.40.1)`

2023-11-14 16:14 UTC, PoomSmart approved these changes

2023-11-17 16:39 UTC, L1ghtmann requested changes
Posting this here for others. Compilation and linking fail on Linux. Seems a number of files in <sdk>/usr/{include,lib} are ASCII when they are meant to be symlinks (e.g., pthread.h in include and libobjc.tbd in lib)

2023-11-18 17:21 UTC, L1ghtmann approved these changes
Turns out the ASCII issue I mentioned was an artifact from an external tool I used to selectively checkout the SDKS. Cloning from git works when tested against 8 projects.

2023-11-18 18:47 UTC, leptos-null commented
Thank you for your extended testing, Lightmann

2023-11-18 18:47 UTC, merged